// Import FirebaseAuth and firebase.
import Head from 'next/head';
import styles from '../styles/Login.module.css';
import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth';
import {getAuth, GithubAuthProvider, EmailAuthProvider} from 'firebase/auth';
import {app} from '../firebase/clientApp';


const auth=getAuth(app);

// Configure FirebaseUI.
const uiConfig = {

    emailLinkSignIn: ()=> 
    {
        return {
            // Additional state showPromo=1234 can be retrieved from URL on
            // sign-in completion in signInSuccess callback by checking
            // window.location.href.
            // If you are using a fragment in the URL, additional FirebaseUI
            // parameters will be appended to the query string component instead
            // of the fragment.
            // So for a url: https://www.example.com/#/signin
            // The completion URL will take the form:
            // https://www.example.com/?uid_sid=xyz&ui_sd=0#/signin
            // This should be taken into account when using frameworks with "hash
            // routing".
            url: 'https://www.example.com/completeSignIn?showPromo=1234',
            // Custom FDL domain.
            dynamicLinkDomain: 'example.page.link',
            // Always true for email link sign-in.
            handleCodeInApp: true,
            // Whether to handle link in iOS app if installed.
            iOS: {
              bundleId: 'com.example.ios'
            },
            // Whether to handle link in Android app if opened in an Android
            // device.
            android: {
              packageName: 'com.example.android',
              installApp: true,
              minimumVersion: '12'
            }
          };
    },

    // Popup signin flow rather than redirect flow.
    signInFlow: 'popup',
    // Redirect to /signedIn after sign in is successful. Alternatively you can provide a callbacks.signInSuccess function.
    signInSuccessUrl: '/test',
    // We will display Google and Facebook as auth providers.
    signInOptions: [
        GithubAuthProvider.PROVIDER_ID,
        EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD
    ]
};

function login() {
    
    return (
        <div>
            <Head>
                 <title>Login</title>
                 <meta name="description" content="Generated by create next app" />
                 <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <label className={styles.loginTitle}>Please Login</label>
            </div>
            <div>
                <StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={auth} />  
            </div>
            
        </div>
    );
}

export default login;