// Import FirebaseAuth and firebase.
import Head from 'next/head';
import styles from '../styles/Login.module.css';
import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth';
import {getAuth, GithubAuthProvider, EmailAuthProvider} from 'firebase/auth';
import {app} from '../firebase/clientApp';


const auth=getAuth(app);

// Configure FirebaseUI.
const uiConfig = {
    // Popup signin flow rather than redirect flow.
    signInFlow: 'popup',
    // Redirect to /signedIn after sign in is successful. Alternatively you can provide a callbacks.signInSuccess function.
    signInSuccessUrl: '/test',
    // We will display Google and Facebook as auth providers.
    signInOptions: [
        GithubAuthProvider.PROVIDER_ID
    ]
};

function login() {
    
    return (
        <div>
            <main>
                <Head>
                    <title>Login</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div>
                    <label className={styles.loginTitle}>Please Login</label>
                </div>
                <div>
                    <StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={auth} />  
                </div>
            </main>
            <footer className={styles.footer}>
                <div>
                    <p>By clicking the buttons above, you acknowledge that you have read, understood, and agree to CSGrader's &nbsp;
                    <a className={styles.footerLink} href='blank'>Terms of Service</a>
                     &nbsp; and &nbsp;
                    <a className={styles.footerLink} href='blank'>Privacy Policy.</a>
                    </p>
                </div>

            </footer>
        </div>
    );
}

export default login;