// Import FirebaseAuth and firebase.
import Head from 'next/head';
import styles from '../styles/Login.module.css';
import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth';
import {getAuth, GithubAuthProvider, EmailAuthProvider} from 'firebase/auth';
import {app} from '../firebase/clientApp';


const auth=getAuth(app);

// Configure FirebaseUI.
const uiConfig = {
    // Popup signin flow rather than redirect flow.
    signInFlow: 'popup',
    // Redirect to /signedIn after sign in is successful. Alternatively you can provide a callbacks.signInSuccess function.
    signInSuccessUrl: '/test',
    // We will display Google and Facebook as auth providers.
    signInOptions: [
        GithubAuthProvider.PROVIDER_ID,
        EmailAuthProvider.EMAIL_LINK_SIGN_IN_METHOD
    ]
};

function login() {
    
    return (
        <div>
            <Head>
                 <title>Login</title>
                 <meta name="description" content="Generated by create next app" />
                 <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.loginContainer}>
                <div className={styles.loginGrid}>
                    <div>
                        <label className={styles.loginTitle}>Please Login</label>
                    </div>
                    <div>
                        <StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={auth} />  
                    </div>
                </div>
            </div>
            
        </div>
    );
}

export default login;