import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import React from 'react';
import {app} from '../firebase/clientApp';
import {getAuth, User} from 'firebase/auth';
import {useAuthState} from 'react-firebase-hooks/auth';
import { StringNullableChain } from 'cypress/types/lodash';


function defaultPage()
{
    return(
        <React.Fragment>
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js login page!</a>
                </h1>
            </main>
        </div>
        </React.Fragment>
    );
}

function loggedPage(user: User)
{
    const authResult = JSON.parse(sessionStorage.getItem('authResult') || '{}') as object;

    return(
        <div>
            <Head>
                <title>Welcome Back</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p>Display name: {user.displayName}</p>
            <p>Email: {user.email}</p>
        </div>
    );
}


 const Login : NextPage = () => {
    const [user, loading, error] = useAuthState(getAuth(app));
    
    if(loading)
    {
        return(
            <div>
                <Head>
                    <title>Loading...</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
        );
    }else
    {
        if(user)
        {
            return loggedPage(user);
        }else
        {
            return defaultPage();
        }
    }
 };
 
export default Login;